sudo: false
dist: trusty
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - python3
            - python3-pip
            - libxcb1-dev
            - libglu1-mesa-dev
            - libgl1-mesa-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && BACKEND=X11GL3"

    - os: linux
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - python3
            - python3-pip
            - libxcb1-dev
            - libglu1-mesa-dev
            - libgl1-mesa-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && BACKEND=X11GL3"

    - os: linux
      compiler: clang-4.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - g++-7
            - clang-4.0
            - python3
            - python3-pip
            - libxcb1-dev
            - libglu1-mesa-dev
            - libgl1-mesa-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0 && BACKEND=X11GL3"

    - os: linux
      compiler: clang-5.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7
            - clang-5.0
            - python3
            - python3-pip
            - libxcb1-dev
            - libglu1-mesa-dev
            - libgl1-mesa-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && BACKEND=X11GL3"

    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-6
    #         - python3
    #         - python3-pip
    #         - libxcb1-dev
    #         - libvulkan-dev
    #   env:
    #     - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && BACKEND=X11VULKAN"

    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-7
    #         - python3
    #         - python3-pip
    #         - libxcb1-dev
    #         - libvulkan-dev
    #   env:
    #     - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && BACKEND=X11VULKAN"

    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - llvm-toolchain-trusty-4.0
    #       packages:
    #         - clang-4.0
    #         - python3
    #         - python3-pip
    #         - libxcb1-dev
    #         - libvulkan-dev
    #   env:
    #     - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0 && BACKEND=X11VULKAN"

    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - llvm-toolchain-trusty-5.0
    #       packages:
    #         - clang-5.0
    #         - python3
    #         - python3-pip
    #         - libxcb1-dev
    #         - libvulkan-dev
    #   env:
    #     - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && BACKEND=X11VULKAN"

before_install:
  - mkdir -p ~/.local/bin
  - eval "${MATRIX_EVAL}"
  - eval "PATH=$PATH:~/.local/bin"
  - curl -LO https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip -d ~/.local/bin

install:
  - pip3 install --user meson

script:
  - meson -Dgfxbackend=$BACKEND build
  - ninja -C build